import { ClosetItem } from "./types";

const BASE = "/closet-defaults";
export const DEFAULT_CLOSET_SEED_VERSION = "2026-08-20-default-v1";

// 默认衣橱用于作品集访客的首次体验：图片放在 public 下，localStorage 只存 URL，
// 避免把 17 张图转成 base64 后撑爆浏览器存储配额。
const CREATED_AT = Date.UTC(2026, 7, 20, 8, 0, 0);

export const DEFAULT_CLOSET_ITEMS: ClosetItem[] = [
  {
    id: "default_lavender_bag",
    name: "Lavender Shoulder Bag",
    category: "Accessories",
    tag: "Bag",
    colorHint: "lavender",
    image: `${BASE}/accessory_lavender_bag.jpg`,
    favorite: false,
    createdAt: CREATED_AT + 16,
  },
  {
    id: "default_black_sunglasses",
    name: "Black Oval Sunglasses",
    category: "Accessories",
    tag: "Eyewear",
    colorHint: "black",
    image: `${BASE}/accessory_black_sunglasses.jpg`,
    favorite: false,
    createdAt: CREATED_AT + 15,
  },
  {
    id: "default_lilac_cardholder",
    name: "Lilac Card Holder",
    category: "Accessories",
    tag: "SLG",
    colorHint: "lilac",
    image: `${BASE}/accessory_lilac_cardholder.jpg`,
    favorite: false,
    createdAt: CREATED_AT + 14,
  },
  {
    id: "default_black_shoulder_bag",
    name: "Black Shoulder Bag",
    category: "Accessories",
    tag: "Bag",
    colorHint: "black",
    image: `${BASE}/accessory_black_shoulder_bag.jpg`,
    favorite: false,
    createdAt: CREATED_AT + 13,
  },
  {
    id: "default_black_graphic_tee",
    name: "Black Graphic Tee",
    category: "Tops",
    tag: "T-Shirt",
    colorHint: "black",
    image: `${BASE}/top_black_graphic_tee.avif`,
    favorite: false,
    createdAt: CREATED_AT + 12,
  },
  {
    id: "default_black_hoodie",
    name: "Black Hoodie",
    category: "Outerwear",
    tag: "Hoodie",
    colorHint: "black",
    image: `${BASE}/outerwear_black_hoodie.avif`,
    favorite: false,
    createdAt: CREATED_AT + 11,
  },
  {
    id: "default_supreme_patchwork_longsleeve",
    name: "Patchwork Long Sleeve",
    category: "Tops",
    tag: "Long Sleeve",
    colorHint: "brown orange",
    image: `${BASE}/top_supreme_patchwork_longsleeve.webp`,
    favorite: false,
    createdAt: CREATED_AT + 10,
  },
  {
    id: "default_pastel_knit_vest",
    name: "Pastel Knit Vest",
    category: "Tops",
    tag: "Knit",
    colorHint: "pastel plaid",
    image: `${BASE}/top_pastel_knit_vest.webp`,
    favorite: false,
    createdAt: CREATED_AT + 9,
  },
  {
    id: "default_plaid_bag",
    name: "Plaid Mini Bag",
    category: "Accessories",
    tag: "Bag",
    colorHint: "pink plaid",
    image: `${BASE}/accessory_plaid_bag.webp`,
    favorite: false,
    createdAt: CREATED_AT + 8,
  },
  {
    id: "default_plaid_shirt",
    name: "Plaid Draped Shirt",
    category: "Outerwear",
    tag: "Shirt",
    colorHint: "blue plaid",
    image: `${BASE}/outerwear_plaid_shirt.webp`,
    favorite: false,
    createdAt: CREATED_AT + 7,
  },
  {
    id: "default_orb_necklace",
    name: "Orb Pendant Necklace",
    category: "Accessories",
    tag: "Jewelry",
    colorHint: "silver",
    image: `${BASE}/accessory_orb_necklace.webp`,
    favorite: false,
    createdAt: CREATED_AT + 6,
  },
  {
    id: "default_black_denim",
    name: "Black Wide Denim",
    category: "Bottoms",
    tag: "Denim",
    colorHint: "black",
    image: `${BASE}/bottom_black_denim.webp`,
    favorite: false,
    createdAt: CREATED_AT + 5,
  },
  {
    id: "default_supreme_red_track_jacket",
    name: "Red Track Jacket",
    category: "Outerwear",
    tag: "Jacket",
    colorHint: "red green",
    image: `${BASE}/outerwear_supreme_red_track_jacket.webp`,
    favorite: false,
    createdAt: CREATED_AT + 4,
  },
  {
    id: "default_blue_supreme_hoodie",
    name: "Blue Hoodie",
    category: "Outerwear",
    tag: "Hoodie",
    colorHint: "sky blue",
    image: `${BASE}/outerwear_blue_supreme_hoodie.webp`,
    favorite: false,
    createdAt: CREATED_AT + 3,
  },
  {
    id: "default_gray_wide_pants",
    name: "Gray Wide Pants",
    category: "Bottoms",
    tag: "Pants",
    colorHint: "gray",
    image: `${BASE}/bottom_gray_wide_pants.webp`,
    favorite: false,
    createdAt: CREATED_AT + 2,
  },
  {
    id: "default_beige_trousers",
    name: "Beige Trousers",
    category: "Bottoms",
    tag: "Trousers",
    colorHint: "beige",
    image: `${BASE}/bottom_beige_trousers.webp`,
    favorite: false,
    createdAt: CREATED_AT + 1,
  },
  {
    id: "default_blue_pink_denim",
    name: "Blue Pink Denim",
    category: "Bottoms",
    tag: "Denim",
    colorHint: "blue pink",
    image: `${BASE}/bottom_blue_pink_denim.webp`,
    favorite: false,
    createdAt: CREATED_AT,
  },
];
